# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import sqlite3



'select makine_adi from makine where bakim_tar=?','guncel_tar'''

class Ui_login(object):
    def handleLogin(self):
        # Kullanıcı adı ve şifreyi alın
            username = self.kullanici_adi.text()
            password = self.sifre.text()

        # SQLite veritabanına bağlanıp kullanıcı bilgilerini kontrol edin
            conn = sqlite3.connect('login.db')
            cursor = conn.cursor()
            query = 'SELECT * FROM users WHERE username=? AND password=?'
            cursor.execute(query, (username, password))
            result = cursor.fetchone()
            if result:
            # Kullanıcı adı ve şifre doğru, giriş işlemini gerçekleştirin
                print('Giriş başarılı!')
            else:
            # Kullanıcı adı ve şifre yanlış, bir hata mesajı gösterin
                print('Kullanıcı adı veya şifre yanlış!')
                msg=QMessageBox()
                msg.setWindowTitle("Giriş Başarısız")
                msg.setText("Kullanıcı adı veya şifre hatalı!")
                msg.exec_()
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(196, 259)
        login.setWindowTitle("Giriş")
        self.centralwidget = QtWidgets.QWidget(login)
        self.centralwidget.setObjectName("centralwidget")
        self.kullanici_adi_label = QtWidgets.QLabel(self.centralwidget)
        self.kullanici_adi_label.setGeometry(QtCore.QRect(10, 70, 61, 16))
        self.kullanici_adi_label.setObjectName("kullanici_adi_label")
        self.sifre_label = QtWidgets.QLabel(self.centralwidget)
        self.sifre_label.setGeometry(QtCore.QRect(40, 90, 21, 16))
        self.sifre_label.setObjectName("sifre_label")
        self.giris = QtWidgets.QPushButton(self.centralwidget)
        self.giris.setGeometry(QtCore.QRect(60, 140, 75, 41))
        self.giris.setObjectName("giris")
        self.giris.clicked.connect(self.handleLogin)
        self.kullanici_adi = QtWidgets.QLineEdit(self.centralwidget)
        self.kullanici_adi.setGeometry(QtCore.QRect(70, 70, 113, 20))
        self.kullanici_adi.setObjectName("kullanici_adi")
        self.sifre = QtWidgets.QLineEdit(self.centralwidget)
        self.sifre.setGeometry(QtCore.QRect(70, 90, 113, 20))
        self.sifre.setObjectName("sifre")
        self.sifre.setEchoMode(QtWidgets.QLineEdit.Password)
        login.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(login)
        self.statusbar.setObjectName("statusbar")
        login.setStatusBar(self.statusbar)
        

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)
       
    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        self.kullanici_adi_label.setText(_translate("login", "Kullanıcı Adı"))
        self.sifre_label.setText(_translate("login", "Şifre"))
        self.giris.setText(_translate("login", "GİRİŞ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login = QtWidgets.QMainWindow()
    ui = Ui_login()
    ui.setupUi(login)
    login.show()
    sys.exit(app.exec_())
